---
- name: Install MySQL on Ubuntu 22.04
  hosts: db
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL Server
      ansible.builtin.apt:
        name: "mysql-server={{ mysql_version }}"
        state: "{{ mysql_state }}"

    - name: Secure Installation of MySQL
      block:
        - name: Ensure MySQL service is running
          ansible.builtin.service:
            name: mysql
            state: started
            enabled: "{{ mysql_enable }}"

  handlers:
    - name: restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted

