---
- name: Install WordPress on Ubuntu 22.04
  hosts: web
  become: true
  vars:
    mysql_root_password: "ChangeMe"
    mysql_db: "wordpress_db"
    mysql_user: "wordpress_user"
    mysql_password: "ChangeMeToo"
    wordpress_url: "http://your_domain.com"
    php_version: "8.1"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - mysql-server
          - php-fpm
          - php-mysql
          - php-cli
          - php-gd
          - php-curl
          - php-xml
        state: present

    - name: Start and enable Nginx and MySQL
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: [nginx, mysql]

    - name: Create MySQL Database
      ansible.builtin.mysql_db:
        name: "{{ mysql_db }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Create MySQL User
      ansible.builtin.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Download WordPress
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: Extract WordPress
      ansible.builtin.unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
        creates: /var/www/wordpress/wp-settings.php

    - name: Configure WordPress
      template:
        src: wp-config.php.j2
        dest: /var/www/wordpress/wp-config.php

    - name: Update Nginx configuration for WordPress
      ansible.builtin.template:
        src: wordpress_nginx.j2
        dest: /etc/nginx/sites-available/wordpress
      notify: Reload Nginx

    - name: Enable WordPress site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

