---
- name: restart nginx
  become: true
  service:
    name    : '{{ nginx }}'
    state   : restarted
    enabled : yes

- name: restart php-fpm
  become: true
  service:
    name    : '{{ php }}'
    state   : restarted
    enabled : yes
    
- name: restart php5-fpm
  become: true
  service:
    name    : '{{ php5 }}'
    state   : restarted
    enabled : yes
    
- name: restart mysql
  become: true
  service:
    name    : '{{ mysql }}'
    state   : restarted
    enabled : yes

