---
- name: restart php-fpm
  become: true
  service:
    name    : '{{ php }}'
    state   : restarted

- name: restart php5-fpm
  become: true
  service:
    name    : '{{ php5 }}'
    state   : restarted
